version: "3.7"
services:
  web:
    image: nginx:1.21.6-alpine
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - 127.0.0.1:8083:80

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - database
    ports:
      - 127.0.0.1:8084:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  database:
    image: postgres:14.2-alpine3.15
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: my-app
      POSTGRES_PASSWORD: ILovePB138
    volumes:
      - database-storage:/var/lib/postgresql/data


volumes:
  database-storage:
